# (PART) Before Arrival {-}

# The Essentials {#chapter-essentials}

Consider this the **too long, didn't read (TLDR)** section of the *most* important tasks to accomplish before departing for your new life in Munich.

## Gather your Documents

A non-exhaustive list of key documents **you will need** to provide in the coming weeks and months:

* Your **passport**
* **High school transcript**
* **High school diploma** (or equivalent)
* Possibly: ACT, SAT, A-levels, or similar high school-leaving tests
* **Bachelor's transcript** (if applicable), **official copy or notarized**
* **Bachelor's grading scale information**; should be available from your university registrar or online
* **Bachelor's diploma** (if applicable), **official copy or notarized**
* **Proof of admission** to your program
* **Curriculum Vitae/Resume**


## Register at Uni

This is an obvious step, but warrants a massive notice because this process can be slow, tedious, and often has **hard** deadlines. I cannot speak to the procedures for all universities nor programs in Munich, but I can provide an anecdote highlighting the process a friend worked through:

1. Applied opnline to their program using the expected documents (e.g. passport, school degrees/transcripts, etc.)
2. Received admission letter from the program via email.
3. Submitted the documents from Steps 1 and 2 to the university's admissions office via an online platform.
4. Admission's office sent an approval letter to the student via the same online platform.
5. Documents from Steps 1, 2, and 4 all had to be sent by **post mail** to the same admissions office from Step 3.

Again, this doesn't represent the process that all students will go through in registering, but does demonstrate how there is lots of back-and-forth and plenty of opportunity for something to go wrong. If you don't hear news or updates on processing, don't hesitate to send emails to your program or the university. Only you are responsible for registering yourself, and most universities will **strictly adhere to their deadlines.** This means, if you don't submit your documents on time, you won't be able to enroll (until the next semester, if your program permits).


## Find an Apartment

Competition for individual apartments and shared flats (Wohungsgemeinschaften) is intense, and this may prove to be the most difficult, time-consuming process of relocating to Munich. Quick tips:

* Use any networks/connections you have in Munich or Germany
* Contact dozens of apartments with thoughtful messages
* Write and speak in German if you can. Otherwise, messages in English are expected.
* Live in a student dorm
* Broaden your search to the outer regions/towns of Munich
* Don't give up

Check out the [Apartment Hunting chapter](#chapter-apartments) for a more detailed look at the process.





