# University Registration {#chapter-uni-registration}


## Important Documents

Unsurprisingly, the uni offices will require a series of documents to prove your previous education and credentials. You have likely already provided digital copies of these documents as part of the application procedure, and some universities will further require that you submit **paper versions** of the documents already submitted online. Note that in such cases, you will absolutely not be able to complete your registration with the university until you provide the paper versions, and there are deadlines for university registration that you must adhere to.

### Typical Documents

As noted in the [Essentials section](#chapter-essentials), there are a minimum of documents you will be expected to provide to your university:

- Previous diplomas
  - Surprisingly, high school degrees are requested (at minimum, up until masters degree programs)
  - Bachelor's degrees
  - Master's degrees
- Official university transcript(s)
- Acceptance letter from the department (if applicable)
- If international, acceptance letter from the international office. (This is true at LMU, and may or may not be the case at other unis too.)

### Certified Copies

Take special care that your diplomas and transcripts are **certified copies** of the original documents. In Germany, such copies are referred to as "Beglaubigte" documents, and may also be referred to as "notarized copies" in English. If a uni requests a certified copy, you **must** provide such a paper copy; nothing else will be accepted.

> Some universities provide official, e-transcripts that are *supposed* to be valid and recognized at other unis and institutions. German universities **will not** accept these, however, as a matter of legality; such e-documents cannot be recognized as "signed" by the university because there is not a physical signature. For that matter, lawyers in German who can perform "Beglaubingungen" will likewise not accept e-documents.


**Documents that need to be certified must either be provided as certified copies from your university registrar or notarized by a notary public. I cannot recommend enough that you obtain multiple notarized/certified copies of such documents before departing for Germany.** My best recommendation is to simply make certified copies prior to departing **and** to bring the original documents with you in case you need to create additional copies at some point.

As a further note, **German universities have special regulations for students who attended uni in certain countries**. That is, the requirements and scrutiny around students who went to uni in e.g. Pakistan and Iran is incredibly strict. Because this is a specialized and uncommon issue, however, I won't provide additional details here.

### Delivery (if required)

As mentioned, some unis require that paper copies of the documents be sent. This should be relatively straight-forward, but some quick tips:

- Double-check the address (obviously)
  - If there are multiple addresses or rooms within a building noted on your documents, send an email to confirm which one is correct. The wrong office is not guaranteed to process or even pass-along incorrectly mailed documents
- **Pay for tracked, certified, or similar mail**
  - Yes, it's much more expensive than sending a standard flat rate letter, but it will save you a massive amount of worry and stressing about whether or not your documents have arrived.
